repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]
        additional_dependencies: []
